name: tickvent
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  custom_navigation_bar: ^0.8.2
  dart_either: ^2.0.0
  dio: ^5.8.0+1
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  path_provider: ^2.1.5
  pinput: ^5.0.0
  pretty_dio_logger: ^1.4.0
  sembast: ^3.8.3
  stacked: ^3.4.0
  stacked_services: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
